name: Deploy-Prod
on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_PROD_ACCESS_TOKEN }}
          aws-secret-access-key: ${{ secrets.AWS_PROD_SECRET }}
          aws-region: us-east-1
      - name: Deploy static site to S3 bucket
        run: aws s3 sync ./docs/ s3://battlescripts
